version: '3.9'


services:
  web:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    command: sh /app/docker/entrypoint.sh
    volumes:
      - ./backend:/app
      - ./docker:/app/docker
      - ./tests:/app/tests
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  celery:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - ./backend:/app
      - ./docker:/app/docker
      - ./tests:/app/tests
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db
  celery-beat:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app
      - ./docker:/app/docker
      - ./tests:/app/tests
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db